name: flutter_tensorflow_audio
description: Sua Musica Talks

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  #UI
  cupertino_icons: ^1.0.2
  lottie: ^1.2.2
  #Image Rec
  # tflite : ^1.1.2
  tflite :
  # camera: ^0.9.4+14
  camera: 
  #Audio Rec
  # tflite_audio: ^0.2.2+4
  tflite_audio: 
  speech_to_text: ^7.0.0
  provider: ^6.1.2
  tflite_flutter: ^0.10.4
  flutter_sound:
  permission_handler: ^11.3.1
  tflite_flutter_helper_plus:

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/audio/labels.txt
    - assets/audio/soundclassifier_with_metadata.tflite
    - assets/y.tflite
    - assets/y.csv
    - assets/sounds/labels.txt
    - assets/sounds/sound512.tflite
    - assets/image/labels.txt
    - assets/image/model_unquant.tflite
    - assets/ui/home_animation.json
    - assets/homeScreen.png

